compilation:
  cloud_properties:
    name: random
  network: redis_z1
  reuse_compilation_vms: true
  workers: 2
director_uuid: <%= `bundle exec bosh status --uuid` %>
jobs:
- instances: 1
  name: cf-redis-broker
  networks:
  - name: redis_z1
    static_ips:
    - 10.244.3.34
  persistent_disk: 8192
  properties:
    broker:
      password: admin
      username: admin
    host: redis-broker.10.244.0.34.xip.io
  resource_pool: redis_z1
  templates:
  - name: cf-redis-broker
    release: cf-redis
  - name: syslog-configurator
    release: cf-redis
- instances: 1
  name: dedicated-node
  networks:
  - name: redis_z1
    static_ips:
    - 10.244.3.38
  persistent_disk: 8192
  resource_pool: redis_z1
  templates:
  - name: dedicated-node
    release: cf-redis
  - name: syslog-configurator
    release: cf-redis
- instances: 1
  lifecycle: errand
  name: broker-registrar
  networks:
  - name: redis_z1
  properties:
    broker:
      host: redis-broker.10.244.0.34.xip.io
      name: redis
      password: admin
      username: admin
  resource_pool: redis_z1
  templates:
  - name: broker-registrar
    release: cf-redis
- instances: 1
  lifecycle: errand
  name: broker-deregistrar
  networks:
  - name: redis_z1
  properties:
    broker:
      host: redis-broker.10.244.0.34.xip.io
      name: redis
      password: admin
      username: admin
  resource_pool: redis_z1
  templates:
  - name: broker-deregistrar
    release: cf-redis
- instances: 1
  lifecycle: errand
  name: smoke-tests
  networks:
  - name: redis_z1
  resource_pool: redis_z1
  templates:
  - name: smoke-tests
    release: cf-redis
meta:
  apps_domain: 10.244.0.34.xip.io
  environment: cf
  external_domain: 10.244.0.34.xip.io
  nats:
    host: 10.244.0.6
    password: nats
    port: 4222
    username: nats
  syslog_aggregator:
    address: 127.0.0.1
    port: 1234
name: cf-redis
networks:
- name: redis_z1
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.3.32/30
    reserved:
    - 10.244.3.33
    static:
    - 10.244.3.34
  - cloud_properties:
      name: random
    range: 10.244.3.36/30
    reserved:
    - 10.244.3.37
    static:
    - 10.244.3.38
  - cloud_properties:
      name: random
    range: 10.244.3.40/30
    reserved:
    - 10.244.3.41
    static:
    - 10.244.3.42
  - cloud_properties:
      name: random
    range: 10.244.3.44/30
    reserved:
    - 10.244.3.45
    static:
    - 10.244.3.46
  - cloud_properties:
      name: random
    range: 10.244.3.48/30
    reserved:
    - 10.244.3.49
    static:
    - 10.244.3.50
  - cloud_properties:
      name: random
    range: 10.244.3.52/30
    reserved:
    - 10.244.3.53
    static:
    - 10.244.3.54
  - cloud_properties:
      name: random
    range: 10.244.3.56/30
    reserved:
    - 10.244.3.57
    static:
    - 10.244.3.58
  - cloud_properties:
      name: random
    range: 10.244.3.60/30
    reserved:
    - 10.244.3.61
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.64/30
    reserved:
    - 10.244.3.65
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.68/30
    reserved:
    - 10.244.3.69
    static: []
properties:
  cf:
    admin_password: admin
    admin_username: admin
    api_url: http://api.10.244.0.34.xip.io
    apps_domain: 10.244.0.34.xip.io
    nats:
      host: 10.244.0.6
      password: nats
      port: 4222
      username: nats
  redis:
    agent:
      backend_port: 54321
    bg_save_command: yetanotherrandomstring
    broker:
      auth:
        password: admin
        username: admin
      backend_host: 10.244.3.34
      backend_port: 12345
      backups:
        access_key_id: YOUR_S3_ACCESS_KEY_ID
        bucket_name: YOUR_S3_BUCKET
        endpoint_url: S3_ENDPOINT_FOR_YOUR_REGION
        path: YOUR_S3_BACKUP_PATH
        secret_access_key: YOUR_S3_SECRET_ACCESS_KEY
      dedicated_nodes:
      - 10.244.3.38
      enable_service_access: true
      name: redis
      network: redis_z1
      service_instance_limit: 5
      service_name: redis
    config_command: configalias
    host: 10.244.3.34
    maxmemory: 262144000
    save_command: anotherrandomstring
  syslog_aggregator:
    address: 127.0.0.1
    port: 1234
releases:
- name: cf-redis
  version: latest
resource_pools:
- cloud_properties:
    name: random
    ram: 1024
  name: redis_z1
  network: redis_z1
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: 389
update:
  canaries: 1
  canary_watch_time: 30000-180000
  max_in_flight: 4
  update_watch_time: 30000-180000

